name: Alpine CI
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches: [master]
  push:
    branches: [master]
concurrency:
  group: alpine-ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-alpine:
    name: Build
    strategy:
      matrix:
        version: ["3.11.13", "3.12.10", "3.13.12", "3.14.8", "3.15.6", "3.16.3", "3.17.1"]
    runs-on: ubuntu-latest
    container:
      image: alpine:${{ matrix.version }}
    steps:
    - uses: actions/checkout@v2
    - run: apk --update add cmake alpine-sdk openssl-dev linux-headers
    - run: ./build.sh
    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: alpine-${{ matrix.version }}binaries
        path: |
          build/bin/cpp-kzg-ceremony-client
          build/bin/cpp-kzg-ceremony-client-test

  test-alpine:
    name: Test
    needs: build-alpine
    strategy:
      matrix:
        version: ["3.11.13", "3.12.10", "3.13.12", "3.14.8", "3.15.6", "3.16.3", "3.17.1"]
    runs-on: ubuntu-latest
    container:
      image: alpine:${{ matrix.version }}
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: alpine-${{ matrix.version }}-binaries
    - run: apk --update add libstdc++
    - run: chmod +x ./cpp-kzg-ceremony-client-test
    - run: ./cpp-kzg-ceremony-client-test

  sanity-check-alpine:
    name: Sanity Check
    needs: build-alpine
    strategy:
      matrix:
        version: ["3.11.13", "3.12.10", "3.13.12", "3.14.8", "3.15.6", "3.16.3", "3.17.1"]
    runs-on: ubuntu-latest
    container:
      image: alpine:${{ matrix.version }}
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: alpine-${{ matrix.version }}-binaries
    - run: apk --update add libstdc++
    - run: chmod +x ./cpp-kzg-ceremony-client
    - run: ./cpp-kzg-ceremony-client --help
