name: Alpine CI
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches: [master]
  push:
    branches: [master]
concurrency:
  group: alpine-ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-alpine:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: alpine:3.1
    steps:
    - uses: actions/checkout@v2
    - run: sudo apk add cmake
    - run: ./build.sh
    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: alpine-binaries
        path: |
          build/bin/cpp-kzg-ceremony-client
          build/bin/cpp-kzg-ceremony-client-test

  test-alpine:
    name: Test
    needs: build-alpine
    strategy:
      matrix:
        version: ["3.1", "3.2", "3.3", "3.4", "3.5", "3.6.5", "3.7.3", "3.8.5", "3.9.6", "3.10.9", "3.11.13", "3.12.10", "3.13.12", "3.14.8", "3.15.6", "3.16.3", "3.17.1"]
    runs-on: ubuntu-latest
    container:
      image: alpine:${{ matrix.version }}
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: alpine-binaries
    - run: chmod +x ./cpp-kzg-ceremony-client-test
    - run: ./cpp-kzg-ceremony-client-test

  sanity-check-alpine:
    name: Sanity Check
    needs: build-alpine
    strategy:
      matrix:
        version: ["3.1", "3.2", "3.3", "3.4", "3.5", "3.6.5", "3.7.3", "3.8.5", "3.9.6", "3.10.9", "3.11.13", "3.12.10", "3.13.12", "3.14.8", "3.15.6", "3.16.3", "3.17.1"]
    runs-on: ubuntu-latest
    container:
      image: alpine:${{ matrix.version }}
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: alpine-binaries
    - run: chmod +x ./cpp-kzg-ceremony-client
    - run: ./cpp-kzg-ceremony-client --help
