name: build
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches: [master]
  push:
    branches: [master]
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: ./build.sh
    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu-binaries
        path: |
          build/bin/cpp-kzg-ceremony-client
          build/bin/cpp-kzg-ceremony-client-test

  test-ubuntu:
    name: Test Ubuntu
    needs: build-ubuntu
    strategy:
      matrix:
        version: ["18.04", "20.04", "22.04", "22.10", "23.04"]
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ matrix.version }}
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: ubuntu-binaries
    - run: chmod +x ./cpp-kzg-ceremony-client-test
    - run: ./cpp-kzg-ceremony-client-test

  test-alpine:
    name: Test Alpine
    needs: build-ubuntu
    strategy:
      matrix:
        version: ["2.6", "2.7", "3.1", "3.2", "3.3", "3.4", "3.5", "3.6.5", "3.7.3", "3.8.5", "3.9.6", "3.10.9", "3.11.13", "3.12.10", "3.13.12", "3.14.8", "3.15.6", "3.16.3", "3.17.1"]
    runs-on: ubuntu-latest
    container:
      image: alpine:${{ matrix.version }}
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: ubuntu-binaries
    - run: chmod +x ./cpp-kzg-ceremony-client-test
    - run: ./cpp-kzg-ceremony-client-test

  sanity-check-ubuntu:
    name: Sanity Check Ubuntu Product Binary
    needs: build-ubuntu
    strategy:
      matrix:
        version: ["18.04", "20.04", "22.04", "22.10", "23.04"]
    runs-on: ubuntu-${{ matrix.version }}
    container:
      image: ubuntu:${{ matrix.version }}
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: ubuntu-binaries
    - run: chmod +x ./cpp-kzg-ceremony-client
    - run: ./cpp-kzg-ceremony-client --help

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./build.bat
    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: windows-binaries
        path: |
          build/bin/Release/cpp-kzg-ceremony-client.exe
          build/bin/Release/cpp-kzg-ceremony-client-test.exe

  test-windows:
    name: Test Windows
    needs: build-windows
    strategy:
      matrix:
        version: [2019, 2022]
    runs-on: windows-${{ matrix.version }}
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: windows-binaries
    - run: .\cpp-kzg-ceremony-client-test.exe

  sanity-check-windows:
    name: Sanity Check Windows Product Binary
    needs: build-windows
    strategy:
      matrix:
        version: [2019, 2022]
    runs-on: windows-${{ matrix.version }}
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: windows-binaries
    - run: .\cpp-kzg-ceremony-client.exe --help

  build-darwin:
    name: Build Darwin
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - run: ./build.sh
    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: darwin-binaries
        path: |
          build/bin/cpp-kzg-ceremony-client
          build/bin/cpp-kzg-ceremony-client-test

  test-darwin:
    name: Test Darwin
    needs: build-darwin
    strategy:
      matrix:
        version: [10.15, 11, 12]
    runs-on: macos-${{ matrix.version }}
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: darwin-binaries
    - run: chmod +x ./cpp-kzg-ceremony-client-test
    - run: ./cpp-kzg-ceremony-client-test

  sanity-check-darwin:
    name: Sanity Check Darwin Product Binary
    needs: build-darwin
    strategy:
      matrix:
        version: [10.15, 11, 12]
    runs-on: macos-${{ matrix.version }}
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: darwin-binaries
    - run: chmod +x ./cpp-kzg-ceremony-client
    - run: ./cpp-kzg-ceremony-client --help
