name: build
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches: [master]
  push:
    branches: [master]
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./build.sh
    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: ubuntu-binaries
        path: |
          build/bin/cpp-kzg-ceremony-client
          build/bin/cpp-kzg-ceremony-client-test

  test-ubuntu:
    name: Test Ubuntu
    needs: build-ubuntu
    strategy:
      matrix:
        version: [18.04, 20.04, 22.04, latest]
    runs-on: ubuntu-${{ matrix.version }}
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: ubuntu-binaries
    - run: chmod +x ./cpp-kzg-ceremony-client-test
    - run: ./cpp-kzg-ceremony-client-test

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./build.bat
    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: windows-binaries
        path: |
          build/bin/Release/cpp-kzg-ceremony-client.exe
          build/bin/Release/cpp-kzg-ceremony-client-test.exe

  test-windows:
    name: Test Windows
    needs: build-windows
    strategy:
      matrix:
        version: [2019, 2022, latest]
    runs-on: windows-${{ matrix.version }}
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: windows-binaries
    - run: ./cpp-kzg-ceremony-client-test.exe

  build-darwin:
    name: Build Darwin
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./build.sh
    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: darwin-binaries
        path: |
          build/bin/cpp-kzg-ceremony-client
          build/bin/cpp-kzg-ceremony-client-test

  test-darwin:
    name: Test Darwin
    needs: build-darwin
    strategy:
      matrix:
        version: [10.15, 11, 12, latest]
    runs-on: macos-${{ matrix.version }}
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        name: darwin-binaries
    - run: chmod +x cpp-kzg-ceremony-client-test
    - run: ./cpp-kzg-ceremony-client-test
