name: build
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches: [master]
  push:
    branches: [master]
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./build.sh
    - run: ./build/bin/cpp-kzg-ceremony-client-test
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./build.bat
    - run: ./build/bin/cpp-kzg-ceremony-client-test
  build-darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./build.sh
    - run: ./build/bin/cpp-kzg-ceremony-client-test
