name: Ubuntu CI
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches: [master]
  push:
    branches: [master]
    tags:
      - "v*"
concurrency:
  group: ubuntu-ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-ubuntu:
    name: Build
    strategy:
      matrix:
        version: ["18.04", "20.04", "22.04", "22.10", "23.04"]
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - run: apt update && apt --yes upgrade
      - run: apt --yes install build-essential libssl-dev git wget
      - run: wget https://github.com/Kitware/CMake/releases/download/v3.25.1/cmake-3.25.1-linux-x86_64.sh
      - run: chmod +x cmake-3.25.1-linux-x86_64.sh
      - run: ./cmake-3.25.1-linux-x86_64.sh --skip-license
      - run: PATH=$PWD/bin:$PATH ./build.sh
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-${{ matrix.version }}-binaries
          path: |
            build/bin/cpp-kzg-ceremony-client
            build/bin/cpp-kzg-ceremony-client-test
            build/bin/initialContribution.json
            build/bin/updatedContribution.json

  test-ubuntu:
    name: Test
    needs: build-ubuntu
    strategy:
      matrix:
        version: ["18.04", "20.04", "22.04", "22.10", "23.04"]
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ matrix.version }}
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-${{ matrix.version }}-binaries
      - run: apt update && apt --yes upgrade
      - run: apt --yes install openssl
      - run: chmod +x ./cpp-kzg-ceremony-client-test
      - run: ./cpp-kzg-ceremony-client-test

  sanity-check-ubuntu:
    name: Sanity Check
    needs: build-ubuntu
    strategy:
      matrix:
        version: ["18.04", "20.04", "22.04", "22.10", "23.04"]
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ matrix.version }}
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-${{ matrix.version }}-binaries
      - run: apt update && apt --yes upgrade
      - run: apt --yes install openssl
      - run: chmod +x ./cpp-kzg-ceremony-client
      - run: ./cpp-kzg-ceremony-client --help

  publish-ubuntu:
    needs: [test-ubuntu, sanity-check-ubuntu]
    # if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["18.04", "20.04", "22.04", "22.10", "23.04"]
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-${{ matrix.version }}-binaries
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - run: tar -czvf cpp-kzg-ceremony-client-${{ github.ref }}-ubuntu-${{ matrix.version }}-amd64.tar.gz cpp-kzg-ceremony-client
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: cpp-kzg-ceremony-client-${{ github.ref }}-ubuntu-${{ matrix.version }}-amd64.tar.gz
          asset_name: cpp-kzg-ceremony-client-${{ github.ref }}-ubuntu-${{ matrix.version }}-amd64
