name: Ubuntu CI
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches: [master]
  push:
    branches: [master]
    tags:
      - "v*"
concurrency:
  group: ubuntu-ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-ubuntu:
    name: Build
    strategy:
      matrix:
        version: ["18.04", "20.04", "22.04"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2
        name: Run ARM commands
        id: runarm
        with:
          arch: armv7
          distro: ubuntu${{ matrix.version }}
          run: |
            apt update && apt --yes upgrade
            apt --yes install build-essential libssl-dev git wget
            wget https://github.com/Kitware/CMake/releases/download/v3.25.1/cmake-3.25.1.tar.gz && \
            tar -xzf cmake-3.25.1.tar.gz && \
            cd cmake-3.25.1 && ./bootstrap && make && cd ..
            PATH=$PWD/cmake-3.25.1/bin:$PATH ./build.sh
            cp -R build /artifacts/build
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-${{ matrix.version }}-armv7-binaries
          path: |
            artifacts/build/bin/cpp-kzg-ceremony-client
            artifacts/build/bin/cpp-kzg-ceremony-client-test
            artifacts/build/bin/initialContribution.json
            artifacts/build/bin/updatedContribution.json
