name: Windows CI
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches: [master]
  push:
    branches: [master]
    tags:
      - "v*"
concurrency:
  group: windows-ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build.bat
      - run: cp build/bin/initialContribution.json build/bin/Release/initialContribution.json
      - run: cp build/bin/updatedContribution.json build/bin/Release/updatedContribution.json
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: windows-binaries
          path: |
            build/bin/Release/cpp-kzg-ceremony-client.exe
            build/bin/Release/cpp-kzg-ceremony-client-test.exe
            build/bin/Release/initialContribution.json
            build/bin/Release/updatedContribution.json

  test-windows:
    name: Test
    needs: build-windows
    strategy:
      matrix:
        version: [2019, 2022]
    runs-on: windows-${{ matrix.version }}
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: windows-binaries
      - run: .\cpp-kzg-ceremony-client-test.exe

  sanity-check-windows:
    name: Sanity Check
    needs: build-windows
    strategy:
      matrix:
        version: [2019, 2022]
    runs-on: windows-${{ matrix.version }}
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: windows-binaries
      - run: .\cpp-kzg-ceremony-client.exe --help

  publish-windows:
    needs: [test-windows, sanity-check-windows]
    if: startsWith(github.ref_name, 'v')
    runs-on: ubuntu-latest
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: windows-binaries
      - run: zip cpp-kzg-ceremony-client-${{ github.ref_name }}-windows-amd64.zip cpp-kzg-ceremony-client.exe
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: cpp-kzg-ceremony-client-${{ github.ref_name }}-windows-amd64.zip
